"""
Document processing service using NotebookLlama
"""

import asyncio
from typing import Dict, Any
from pathlib import Path

from app.core.config import settings


class DocumentProcessor:
    """Document processing using NotebookLlama"""
    
    def __init__(self):
        self.notebookllama_available = False
        self.workflow = None
        
        # Try to import NotebookLlama components
        try:
            # Import from the inbox-zero/notebookllama directory
            import sys
            sys.path.append("/Users/bartlomiejflorczak/CascadeProjects/inbox-zero/notebookllama/src")
            
            from notebookllama.workflow import NotebookLMWorkflow, FileInputEvent
            from notebookllama.audio import PODCAST_GEN, PodcastConfig
            
            self.workflow = NotebookLMWorkflow(timeout=600)
            self.FileInputEvent = FileInputEvent
            self.notebookllama_available = True
            print("✅ NotebookLlama components loaded successfully")
            
        except ImportError as e:
            print(f"⚠️  NotebookLlama not available: {e}")
            print("🎭 Using mock processing for development")
            self.notebookllama_available = False
    
    async def process_document(
        self, 
        file_path: str, 
        title: str, 
        document_id: str
    ) -> Dict[str, Any]:
        """
        Process a document and extract insights
        """
        
        if self.notebookllama_available and self.workflow:
            return await self._process_with_notebookllama(file_path, title)
        else:
            return await self._process_mock(file_path, title)
    
    async def _process_with_notebookllama(
        self, 
        file_path: str, 
        title: str
    ) -> Dict[str, Any]:
        """Process document using real NotebookLlama"""
        
        try:
            print(f"🔄 Processing document with NotebookLlama: {title}")
            
            # Create file input event and run workflow
            with open(file_path, 'rb') as f:
                file_event = self.FileInputEvent(file=f, filename=title)
                result = await self.workflow.run(file_event=file_event)
                
                # Extract results
                return {
                    "summary": getattr(result, 'summary', None),
                    "bullet_points": getattr(result, 'bullet_points', None),
                    "q_and_a": getattr(result, 'q_and_a', None),
                    "mindmap_html": getattr(result, 'mindmap_html', None)
                }
                
        except Exception as e:
            print(f"❌ NotebookLlama processing failed: {e}")
            # Fall back to mock processing
            return await self._process_mock(file_path, title)
    
    async def _process_mock(self, file_path: str, title: str) -> Dict[str, Any]:
        """Mock document processing for development"""
        
        print(f"🎭 Mock processing document: {title}")
        
        # Simulate processing time
        await asyncio.sleep(1)
        
        # Read file content for better mock responses
        try:
            with open(file_path, 'rb') as f:
                content = f.read()
                content_preview = str(content[:500])  # First 500 chars
        except:
            content_preview = "Unable to read file content"
        
        return {
            "summary": f"📄 **Summary of '{title}'**\n\nThis document has been analyzed using NotebookBobu's AI processing capabilities. The document contains {len(content_preview)} characters of content and covers various important topics. This summary provides a high-level overview of the key themes and insights discovered through automated analysis.\n\n*Note: This is a mock summary for development/testing purposes.*",
            
            "bullet_points": f"• **Document Title**: {title}\n• **Content Analysis**: Comprehensive text analysis completed\n• **Key Themes**: Multiple important topics identified\n• **Structure**: Well-organized document with clear sections\n• **Insights**: Valuable information extracted and categorized\n• **AI Processing**: Advanced natural language understanding applied\n\n*Generated by NotebookBobu AI*",
            
            "q_and_a": f"**Q: What is this document about?**\nA: This document titled '{title}' contains important information that has been processed by NotebookBobu's AI system. The content has been analyzed for key themes, insights, and actionable information.\n\n**Q: What are the main topics covered?**\nA: The document covers several key areas that have been identified through AI analysis. Each topic has been categorized and summarized for easy understanding.\n\n**Q: How can I use this information?**\nA: The processed information can be used for research, decision-making, and gaining deeper insights into the subject matter presented in the original document.",
            
            "mindmap_html": f"""
                <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
                    <h2 style="text-align: center; color: #333;">📋 Document Mind Map: {title}</h2>
                    <div style="background: #f8f9fa; border-radius: 8px; padding: 20px; margin: 20px 0;">
                        <div style="display: flex; justify-content: center; margin-bottom: 30px;">
                            <div style="background: #007bff; color: white; padding: 15px 25px; border-radius: 50px; font-weight: bold; text-align: center;">
                                {title}
                            </div>
                        </div>
                        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px;">
                            <div style="background: white; padding: 15px; border-radius: 8px; border-left: 4px solid #28a745;">
                                <h4 style="margin: 0 0 10px 0; color: #28a745;">📝 Content Analysis</h4>
                                <p style="margin: 0; font-size: 14px;">Comprehensive document processing completed</p>
                            </div>
                            <div style="background: white; padding: 15px; border-radius: 8px; border-left: 4px solid #ffc107;">
                                <h4 style="margin: 0 0 10px 0; color: #ffc107;">🎯 Key Insights</h4>
                                <p style="margin: 0; font-size: 14px;">Important themes and topics identified</p>
                            </div>
                            <div style="background: white; padding: 15px; border-radius: 8px; border-left: 4px solid #dc3545;">
                                <h4 style="margin: 0 0 10px 0; color: #dc3545;">🤖 AI Processing</h4>
                                <p style="margin: 0; font-size: 14px;">Advanced natural language understanding</p>
                            </div>
                            <div style="background: white; padding: 15px; border-radius: 8px; border-left: 4px solid #6f42c1;">
                                <h4 style="margin: 0 0 10px 0; color: #6f42c1;">💡 Actionable Data</h4>
                                <p style="margin: 0; font-size: 14px;">Ready for analysis and decision-making</p>
                            </div>
                        </div>
                        <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #dee2e6;">
                            <small style="color: #6c757d;">Generated by NotebookBobu AI • Document ID: {file_path.split('/')[-1]}</small>
                        </div>
                    </div>
                </div>
            """
        }